Add unique toast and show inside Ui supports
ItsEthra/egui-notify pull request #19
Opened 2023-10-22 13:35 UTC by varphone

New features:
- Add an optional `id` to Toast, could be use a unique id to update an exists toast.
- Add `show_inside()` to Toasts, could be limit the display rect to Ui.
- Add some builder pattern api and setters to Toast and Toasts.

2023-10-23 19:34 UTC, ItsEthra commented
Could describe some use cases for a `show_inside` function?

2023-10-24 00:58 UTC, varphone commented
> Could describe some use cases for a `show_inside` function?

For example: show and clip the notify in a window or panel.

2023-10-24 10:38 UTC, ItsEthra commented
![image](https://github.com/ItsEthra/egui-notify/assets/107059409/1979b3d6-0c44-4684-870f-e845aa00e7f1)
Is seems like there is a small padding on the x axis that probably shouldn't be there.

2023-10-26 10:52 UTC, ItsEthra requested changes

2024-01-09 06:34 UTC, closed without merging