Update README.md
ItsEthra/egui-notify pull request #31
Opened 2024-08-28 16:19 UTC by edvorg

update code example in readme

2024-09-15 05:52 UTC, edvorg commented
@ItsEthra could you please have a look?

2024-09-23 06:48 UTC, ItsEthra commented
Maybe a good idea would be to have the `set_duration` function accept `impl Into<Option<Duration>>` instead?

2024-09-23 07:35 UTC, edvorg commented
@ItsEthra sounds great! Updated the branch with suggested changes

2024-09-23 10:19 UTC, ItsEthra requested changes

2024-09-23 10:19 UTC, ItsEthra commented on README.md
> +toasts.info("Hello world!").set_duration(Some(Duration::from_secs(5)));
I think you forgot to remove that

2024-09-23 10:46 UTC, edvorg commented on README.md
> +toasts.info("Hello world!").set_duration(Some(Duration::from_secs(5)));
Right, it's no longer need, updated

2024-09-25 12:35 UTC, ItsEthra commented
Thanks.

2024-09-25 12:35 UTC, merged